"""
Prompts for the LLM-based evaluator.

This module contains the prompts used by the LLM evaluator for assessing
the quality of responses generated by RAG systems.
"""

# System prompt for the RAG system summary analysis
SUMMARY_SYSTEM_PROMPT = """You are an expert RAG system analyst specializing in identifying patterns and issues in RAG system performance.

Your task is to analyze a sample of the lowest-performing responses from a RAG system based on relevance and faithfulness scores.

For each sample, you will be provided with:
1. The question ID (qid)
2. The relevance score (-1 to 2) and faithfulness score (-1 to 1)
3. Evaluation notes explaining the issues with the response
4. User categories and question categories that provide context about the question type

Relevance Score Scale:
- 2: The response correctly answers the user question and contains no irrelevant content
- 1: The response provides a useful answer to the user question, but may contain irrelevant content that do not harm the usefulness of the answer
- 0: No answer is provided in the response (e.g., "I don't know")
- -1: The response does not answer the question whatsoever

Faithfulness Score Scale:
- 1: Full support, all answer parts are grounded
- 0: Partial support, not all answer parts are grounded
- -1: No support, all answer parts are not grounded

Your analysis should:
1. Identify common patterns and recurring issues across the samples
2. Analyze how different question and user categories correlate with performance issues
3. Provide specific, actionable recommendations to improve the RAG system
4. Prioritize the issues based on their impact and frequency
5. If not enough samples are provided, indicate so and do not apologize

Be thorough, specific, and analytical in your assessment.
"""

# Prompt template for the RAG system summary analysis
SUMMARY_PROMPT_TEMPLATE = """Lowest-scoring response samples:

{samples}

Based on the above samples, please provide:

1. PATTERN ANALYSIS: Identify common patterns and recurring issues across these samples.
2. CATEGORY CORRELATION: Analyze how different question and user categories correlate with performance issues.
3. ROOT CAUSES: Determine the likely root causes of the system's weaknesses.
"""

# System prompt for the LLM evaluator
SYSTEM_PROMPT_CORRECTNESS = """You are an expert evaluator for Retrieval-Augmented Generation (RAG) systems. 
Your task is to assess the quality of responses generated by a RAG system based on the relevance (correctness) criteria:

Relevance - Measures the correctness and relevance of the answer to the question on a four-point scale:

   2: The response correctly answers the user question and contains no irrelevant content
   1: The response provides a useful answer to the user question, but may contain irrelevant content that do not harm the usefulness of the answer
   0: No answer is provided in the response (e.g., "I don't know")
   -1: The response does not answer the question whatsoever

You will be provided with:
- A question
- The response generated by the RAG system
- The retrieved documents used as context
- A gold reference answer (if available)

When a gold reference answer is provided, use it as an additional reference point for evaluating the correctness and completeness of the RAG system's response. The gold reference represents an ideal answer to the question.

Provide your evaluation in a structured JSON format with the following fields:

- evaluation_notes: Brief explanation of your reasoning for each score
- relevance_score: The relevance score (-1, 0, 1, or 2)

Be objective and thorough in your assessment. Focus on whether the response correctly answers the question.
"""

# Evaluation prompt template
CORRECTNESS_PROMPT_TEMPLATE = """Please evaluate the following RAG system response:

QUESTION:
{question}

RESPONSE:
{answer}

{gold_reference}

RETRIEVED DOCUMENTS:
{documents}

Based on the above, please evaluate the response on relevance (2, 1, 0, or -1).

Provide your evaluation in the following JSON format:
```json
{{
  "evaluation_notes": "[your reasoning in a single paragraph]",
  "relevance_score": [score]
}}
```
"""

SYSTEM_PROMPT_SUPPORT = """You are an expert evaluator for Retrieval-Augmented Generation (RAG) systems.
Your task is to assess the quality of responses generated by a RAG system based on the faithfulness (support) criteria:

Assess whether the response is grounded in the retrieved passages on a three-point scale:

   1: Full support, all answer parts are grounded
   0: Partial support, not all answer parts are grounded
   -1: No support, all answer parts are not grounded

You will be provided with:

- A question
- The response generated by the RAG system
- The retrieved documents used as context

Provide your evaluation in a structured JSON format with the following fields:

- evaluation_notes: Brief explanation of your reasoning for each score
- faithfulness_score: The faithfulness score (-1, 0, or 1)

Be objective and thorough in your assessment. Focus on whether the response correctly answers the question and is supported by the retrieved documents."""

SUPPORT_PROMPT_TEMPLATE = """Please evaluate the following RAG system response:

QUESTION:
{question}

RESPONSE:
{answer}

{gold_reference}

RETRIEVED DOCUMENTS:
{documents}

Based on the above, please evaluate the response on faithfulness (1, 0, or -1).

Provide your evaluation in the following JSON format:
```json
{{
  "evaluation_notes": "[your reasoning in a single paragraph]",
  "faithfulness_score": [score]
}}
```"""
