# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional

from openai.types.chat.chat_completion_chunk import ChoiceDelta as BaseChoiceDelta, Choice as BaseChoice, ChatCompletionChunk as BaseChunk


class CustomChoiceDelta(BaseChoiceDelta):
    # Cerebras Qwen3 model returns this
    reasoning_content: Optional[str] = None
    # Cerebras gpt-oss model returns this
    reasoning: Optional[str] = None


class CustomChoice(BaseChoice):
    delta: CustomChoiceDelta
    """A chat completion delta generated by streamed model responses."""


class CustomChatCompletionChunk(BaseChunk):
    choices: List[CustomChoice]
    """A list of chat completion choices.

    Can contain more than one elements if `n` is greater than 1. Can also be empty
    for the last chunk if you set `stream_options: {"include_usage": true}`.
    """
